model:
  name: GCN
  hidden_dim: 256
  num_layers: 2
  dropout: 0.7

train:
  lr: 0.005
  weight_decay: 5e-4
  epochs: 1000
  patience: 100

plot:
  layer_values: [2, 3, 4, 5, 6]
  compare_models: [GCN]
